nome = input ("Qual seu nome?")
sobrenome = input ("Qual seu sobrenome?")
altura = float(input ("Qual sua altura em cm?"))
peso = float(input ("Qual seu peso?"))
idade = int(input ("Qual sua idade?"))
adulto = idade >= 18
print ("Seu nome é:",idade)
print ("Seu sobrenome é:",sobrenome)
print ("Sua altura é:",altura,"cm")
print ("Seu peso é :",peso,"kg")
print ("Você é um adulto" if adulto else "Você não é um adulto")